// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Channel struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	Name        string
	IsPrivate   bool
	ChannelType string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Message struct {
	ID        pgtype.UUID
	ChannelID pgtype.UUID
	UserID    pgtype.UUID
	ParentID  pgtype.UUID
	Content   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type MessageReaction struct {
	MessageID pgtype.UUID
	UserID    pgtype.UUID
	Emoji     string
	CreatedAt pgtype.Timestamptz
}

type ChannelReadState struct {
	ChannelID  pgtype.UUID
	UserID     pgtype.UUID
	LastReadAt pgtype.Timestamptz
}

type PushSubscription struct {
	UserID    pgtype.UUID
	Endpoint  string
	P256dh    string
	Auth      string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	Username     string
	AvatarUrl    pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Workspace struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	OwnerID   pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
