// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSubscriptionByUsername = `-- name: GetSubscriptionByUsername :one
SELECT ps.endpoint, ps.p256dh, ps.auth
FROM push_subscriptions ps
JOIN users u ON ps.user_id = u.id
WHERE u.username = $1 LIMIT 1
`

type GetSubscriptionByUsernameRow struct {
	Endpoint string
	P256dh   string
	Auth     string
}

func (q *Queries) GetSubscriptionByUsername(ctx context.Context, username string) (GetSubscriptionByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByUsername, username)
	var i GetSubscriptionByUsernameRow
	err := row.Scan(&i.Endpoint, &i.P256dh, &i.Auth)
	return i, err
}

const savePushSubscription = `-- name: SavePushSubscription :exec
INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth)
VALUES ($1, $2, $3, $4)
ON CONFLICT (endpoint) DO UPDATE 
SET user_id = EXCLUDED.user_id, p256dh = EXCLUDED.p256dh, auth = EXCLUDED.auth
`

type SavePushSubscriptionParams struct {
	UserID   pgtype.UUID
	Endpoint string
	P256dh   string
	Auth     string
}

func (q *Queries) SavePushSubscription(ctx context.Context, arg SavePushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, savePushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
	)
	return err
}
